name: Build Anaconda3 Debian Image
on:
  push:
    branches:
      - master
    tags:
      - 'anaconda3-*'
    paths:
      - 'anaconda3/debian/Dockerfile'
      - '.github/workflows/anaconda_debian_ci.yml'
  pull_request:
    paths:
      - 'anaconda3/debian/Dockerfile'
      - '.github/workflows/anaconda_debian_ci.yml'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3

      - name: Login to DockerHub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a # tag=v2
        if: github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags')
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@2b82ce82d56a2a04d2637cd93a637ae1b359c0a7 # v2
        with:
          platforms: linux/amd64,linux/arm64/v8,linux/ppc64le,linux/s390x

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@4b4e9c3e2d4531116a6f8ba8e71fc6e2cb6e6c8c # v2
        with:
          version: latest
          driver-opts: network=host

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@c4ee3adeed93b1fa6a762f209fb01608c1a22f1e # v4
        with:
          images: |
            continuumio/anaconda3
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=match,pattern=anaconda3-(.*),group=1

      - name: build-push anaconda3/debian
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671 # v4
        with:
          context: ./anaconda3/debian
          builder: ${{ steps.buildx.outputs.name }}
          file: ./anaconda3/debian/Dockerfile
          platforms: linux/amd64,linux/arm64/v8,linux/ppc64le,linux/s390x
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          push: ${{ github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags') }}
