name: Build Anaconda3 amazonlinux Image
on:
  push:
    branches:
      - master
    tags:
      - 'anaconda3-*'
    paths:
      - 'anaconda3/amazonlinux/Dockerfile'
      - '.github/workflows/anaconda_amazonlinux_ci.yml'
  pull_request:
    paths:
      - 'anaconda3/amazonlinux/Dockerfile'
      - '.github/workflows/anaconda_amazonlinux_ci.yml'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3 # v3

      - name: Login to DockerHub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a # tag=v2
        if: github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags')
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@e81a89b1732b9c48d79cd809d8d81d79c4647a18 # tag=v2
        with:
          platforms: linux/arm64/v8

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@4b4e9c3e2d4531116a6f8ba8e71fc6e2cb6e6c8c # v2
        with:
          version: latest
          driver-opts: network=host

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@c4ee3adeed93b1fa6a762f209fb01608c1a22f1e # tag=v4
        with:
          images: |
            continuumio/anaconda3
          tags: |
            type=ref,event=branch,suffix=-amazonlinux
            type=ref,event=pr,suffix=-amazonlinux
            type=match,pattern=anaconda3-(.*),group=1,suffix=-amazonlinux
          flavor: |
            latest=false

      - name: build-push anaconda3/amazonlinux
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671 # v4
        with:
          context: ./anaconda3/amazonlinux
          builder: ${{ steps.buildx.outputs.name }}
          file: ./anaconda3/amazonlinux/Dockerfile
          platforms: linux/arm64/v8
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          push: ${{ github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags') }}
