name: Build Anaconda3 Debian Image
on:
  push:
    tags:
      - 'anaconda3-*'
    paths:
      - 'anaconda3/debian/Dockerfile'
      - '.github/workflows/anaconda_debian_ci.yml'
  pull_request:
    paths:
      - 'anaconda3/debian/Dockerfile'
      - '.github/workflows/anaconda_debian_ci.yml'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b

      - name: Login to DockerHub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a # tag=v2
        if: github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags')
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@8b122486cedac8393e77aa9734c3528886e4a1a8 # tag=v2
        with:
          platforms: linux/amd64,linux/arm64/v8,linux/ppc64le,linux/s390x

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@8c0edbc76e98fa90f69d9a2c020dcb50019dc325 # tag=v2
        with:
          version: latest
          driver-opts: network=host

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@57396166ad8aefe6098280995947635806a0e6ea # tag=v4
        with:
          images: |
            continuumio/anaconda3
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=match,pattern=anaconda3-(.*),group=1

      - name: build-push anaconda3/debian
        uses: docker/build-push-action@c56af957549030174b10d6867f20e78cfd7debc5 # tag=v3
        with:
          context: ./anaconda3/debian
          builder: ${{ steps.buildx.outputs.name }}
          file: ./anaconda3/debian/Dockerfile
          platforms: linux/amd64,linux/arm64/v8,linux/ppc64le,linux/s390x
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          push: ${{ github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags') }}
