name: Build and publish Linux package builder images for LTS
on:
  push:
    branches:
      - main
    tags:
      - 'lts-pkg-build-*'
    paths:
      - 'anaconda-pkg-build-lts/linux/Dockerfile'
      - '.github/workflows/anaconda_pkg_build_lts_linux.yml'
  pull_request:
    paths:
      - 'anaconda-pkg-build-lts/linux/Dockerfile'
      - '.github/workflows/anaconda_pkg_build_lts_linux.yml'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # v4

      - name: Login to DockerHub
        uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # v3
        if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags')
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to Public ECR
        uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # v3
        if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags')
        with:
          registry: public.ecr.aws
          username: ${{ secrets.AWS_ACCESS_KEY_ID }}
          password: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        env:
          AWS_REGION: us-east-1

      - name: Set up QEMU
        uses: docker/setup-qemu-action@68827325e0b33c7199eb31dd4e31fbe9023e06e3 # v3

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@0d103c3126aa41d772a8362f6aa67afac040f80c # v3
        with:
          version: latest
          driver-opts: network=host

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@8e5442c4ef9f78752691e2d8f8d19755c6f78e81 # v5
        with:
          images: |
            continuumio/anaconda-pkg-build
            public.ecr.aws/y0o4y9o3/anaconda-pkg-build
          tags: |
            type=ref,event=branch,suffix=-lts
            type=ref,event=pr,suffix=-lts
            type=match,pattern=lts-pkg-build-(.*),group=1,suffix=-lts
          flavor: |
            latest=false

      - name: build-push pkg-builder
        uses: docker/build-push-action@af5a7ed5ba88268d5278f7203fb52cd833f66d6e # v5
        with:
          context: ./anaconda-pkg-build-lts/linux
          builder: ${{ steps.buildx.outputs.name }}
          file: ./anaconda-pkg-build-lts/linux/Dockerfile
          platforms: linux/amd64,linux/arm64/v8,linux/s390x
          build-args: |
            BASEVERSION=7
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          push: ${{ github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags') }}
