name: Build Anaconda3 Debian Image
on:
  push:
    branches:
      - main
    tags:
      - 'anaconda3-*'
    paths:
      - 'anaconda3/debian/Dockerfile'
      - '.github/workflows/anaconda_debian_ci.yml'
  pull_request:
    paths:
      - 'anaconda3/debian/Dockerfile'
      - '.github/workflows/anaconda_debian_ci.yml'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # v4

      - name: Login to DockerHub
        uses: docker/login-action@e92390c5fb421da1463c202d546fed0ec5c39f20 # v3
        if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags')
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@68827325e0b33c7199eb31dd4e31fbe9023e06e3 # v3
        with:
          platforms: linux/amd64,linux/arm64/v8,linux/s390x

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@0d103c3126aa41d772a8362f6aa67afac040f80c # v3
        with:
          version: latest
          driver-opts: network=host

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@8e5442c4ef9f78752691e2d8f8d19755c6f78e81 # v5
        with:
          images: |
            continuumio/anaconda3
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=match,pattern=anaconda3-(.*),group=1

      - name: build-push anaconda3/debian
        uses: docker/build-push-action@2cdde995de11925a030ce8070c3d77a52ffcf1c0 # v5
        with:
          context: ./anaconda3/debian
          builder: ${{ steps.buildx.outputs.name }}
          file: ./anaconda3/debian/Dockerfile
          platforms: linux/amd64,linux/arm64/v8,linux/s390x
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          push: ${{ github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags') }}
