name: Build Anaconda3 amazonlinux Image
on:
  push:
    branches:
      - master
    tags:
      - 'anaconda3-*'
    paths:
      - 'anaconda3/amazonlinux/Dockerfile'
      - '.github/workflows/anaconda_amazonlinux_ci.yml'
  pull_request:
    paths:
      - 'anaconda3/amazonlinux/Dockerfile'
      - '.github/workflows/anaconda_amazonlinux_ci.yml'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3

      - name: Login to DockerHub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a # tag=v2
        if: github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags')
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@e81a89b1732b9c48d79cd809d8d81d79c4647a18 # tag=v2
        with:
          platforms: linux/arm64/v8

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@15c905b16b06416d2086efa066dd8e3a35cc7f98 # tag=v2
        with:
          version: latest
          driver-opts: network=host

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@507c2f2dc502c992ad446e3d7a5dfbe311567a96 # tag=v4
        with:
          images: |
            continuumio/anaconda3
          tags: |
            type=ref,event=branch,suffix=-amazonlinux
            type=ref,event=pr,suffix=-amazonlinux
            type=match,pattern=anaconda3-(.*),group=1,suffix=-amazonlinux
          flavor: |
            latest=false

      - name: build-push anaconda3/amazonlinux
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671 # tag=v3
        with:
          context: ./anaconda3/amazonlinux
          builder: ${{ steps.buildx.outputs.name }}
          file: ./anaconda3/amazonlinux/Dockerfile
          platforms: linux/arm64/v8
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          push: ${{ github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags') }}
