name: Build Anaconda3 amazonlinux Image
on:
  push:
    branches:
      - main
    tags:
      - 'anaconda3-*'
    paths:
      - 'anaconda3/amazonlinux/Dockerfile'
      - '.github/workflows/anaconda_amazonlinux_ci.yml'
  pull_request:
    paths:
      - 'anaconda3/amazonlinux/Dockerfile'
      - '.github/workflows/anaconda_amazonlinux_ci.yml'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v3

      - name: Login to DockerHub
        uses: docker/login-action@465a07811f14bebb1938fbed4728c6a1ff8901fc # v2
        if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags')
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@2b82ce82d56a2a04d2637cd93a637ae1b359c0a7 # v2
        with:
          platforms: linux/arm64/v8

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@885d1462b80bc1c1c7f0b00334ad271f09369c55 # v2
        with:
          version: latest
          driver-opts: network=host

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@818d4b7b91585d195f67373fd9cb0332e31a7175 # v4
        with:
          images: |
            continuumio/anaconda3
          tags: |
            type=ref,event=branch,suffix=-amazonlinux
            type=ref,event=pr,suffix=-amazonlinux
            type=match,pattern=anaconda3-(.*),group=1,suffix=-amazonlinux
          flavor: |
            latest=false

      - name: build-push anaconda3/amazonlinux
        uses: docker/build-push-action@4e4ee680f69700760d5620a94c020aef883043aa # v4
        with:
          context: ./anaconda3/amazonlinux
          builder: ${{ steps.buildx.outputs.name }}
          file: ./anaconda3/amazonlinux/Dockerfile
          platforms: linux/arm64/v8
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          push: ${{ github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags') }}
