name: Build Anaconda3 Alpine Image
on:
  push:
    paths:
      - 'anaconda3/alpine/Dockerfile'
      - '.github/workflows/anaconda_alpine_ci.yml'
  pull_request:
    paths:
      - 'anaconda3/alpine/Dockerfile'
      - '.github/workflows/anaconda_alpine_ci.yml'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@1e204e9a9253d643386038d443f96446fa156a97

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@94ab11c41e45d028884a99163086648e898eed25
        with:
          version: latest
          driver-opts: network=host

      - name: build anaconda3/alpine
        uses: docker/build-push-action@a66e35b9cbcf4ad0ea91ffcaf7bbad63ad9e0229
        with:
          context: ./anaconda3/alpine
          builder: ${{ steps.buildx.outputs.name }}
          file: ./anaconda3/alpine/Dockerfile
          tags: continuumio/anaconda3/alpine:latest
          push: false
