name: Build and publish package builder images
on:
  pull_request:
    paths:
      - 'anaconda-pkg-build/**/Dockerfile'
      - '.github/workflows/anaconda_pkg_build.yml'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f

      - name: Login to DockerHub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        if: github.ref == 'refs/heads/master'
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@0d9a5be0dceea74e09396820e1e522ba4a110d2f
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@aaf69d68aa3fb14c1d5a6be9ac61fe15b48453a2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@27d0a4f181a40b142cce983c5393082c365d1480

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@abe5d8f79a1606a2d3e218847032f3f2b1726ab0
        with:
          version: latest
          driver-opts: network=host

      - name: build-push pkg-builder
        uses: docker/build-push-action@a66e35b9cbcf4ad0ea91ffcaf7bbad63ad9e0229
        with:
          context: ./anaconda-pkg-build/linux
          builder: ${{ steps.buildx.outputs.name }}
          file: ./anaconda-pkg-build/linux/Dockerfile
          platforms: linux/amd64,linux/ppc64le,linux/arm64/v8,linux/s390x
          build-args: |
            BASEVERSION=7
          tags: |
            continuumio/anaconda-pkg-build:cos7
            ${{ steps.login-ecr.outputs.registry }}/anaconda-pkg-build:cos7
          push: ${{ github.ref == 'refs/heads/master' }}
