name: Build and publish the concourse-rsync-resource image
on:
  push:
    tags:
      - 'crr-*'
    paths:
      - 'concourse-rsync-resource/Dockerfile'
      - '.github/workflows/concourse_rsync_resource.yml'
  pull_request:
    paths:
      - 'concourse-rsync-resource/Dockerfile'
      - '.github/workflows/concourse_rsync_resource.yml'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b
        with:
          submodules: true

      - name: Login to DockerHub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a # tag=v2
        if: github.ref == 'refs/heads/master'
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to Public ECR
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a # tag=v2
        if: github.ref == 'refs/heads/master'
        with:
          registry: public.ecr.aws
          username: ${{ secrets.AWS_ACCESS_KEY_ID }}
          password: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        env:
          AWS_REGION: us-east-1

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@8c0edbc76e98fa90f69d9a2c020dcb50019dc325 # tag=v2
        with:
          version: latest
          driver-opts: network=host

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@57396166ad8aefe6098280995947635806a0e6ea # tag=v4
        with:
          images: |
            continuumio/concourse-rsync-resource
            public.ecr.aws/y0o4y9o3/concourse-rsync-resource
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=match,pattern=crr-(.*),group=1

      - name: build-push
        uses: docker/build-push-action@c56af957549030174b10d6867f20e78cfd7debc5 # tag=v3
        with:
          context: ./concourse-rsync-resource
          builder: ${{ steps.buildx.outputs.name }}
          file: ./concourse-rsync-resource/Dockerfile
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          push: ${{ github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags') }}
