name: Build and publish the concourse-rsync-resource image
on:
  push:
    branches:
      - master
    tags:
      - 'crr-*'
    paths:
      - 'concourse-rsync-resource/Dockerfile'
      - '.github/workflows/concourse_rsync_resource.yml'
  pull_request:
    paths:
      - 'concourse-rsync-resource/Dockerfile'
      - '.github/workflows/concourse_rsync_resource.yml'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@24cb9080177205b6e8c946b17badbe402adc938f # v3
        with:
          submodules: true

      - name: Login to DockerHub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a # tag=v2
        if: github.ref == 'refs/heads/master'
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to Public ECR
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a # tag=v2
        if: github.ref == 'refs/heads/master'
        with:
          registry: public.ecr.aws
          username: ${{ secrets.AWS_ACCESS_KEY_ID }}
          password: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        env:
          AWS_REGION: us-east-1

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@4b4e9c3e2d4531116a6f8ba8e71fc6e2cb6e6c8c # v2
        with:
          version: latest
          driver-opts: network=host

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@507c2f2dc502c992ad446e3d7a5dfbe311567a96 # tag=v4
        with:
          images: |
            continuumio/concourse-rsync-resource
            public.ecr.aws/y0o4y9o3/concourse-rsync-resource
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=match,pattern=crr-(.*),group=1

      - name: build-push
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671 # v4
        with:
          context: ./concourse-rsync-resource
          builder: ${{ steps.buildx.outputs.name }}
          file: ./concourse-rsync-resource/Dockerfile
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          push: ${{ github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags') }}
