name: Lint with Hadolint
on:
  pull_request:
    paths:
      - '**/Dockerfile'
      - '.github/workflows/lint.yml'
  push:
    paths:
      - '**/Dockerfile'
      - '.github/workflows/lint.yml'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846
      - name: Lint Dockerfiles
        run: |
          echo "::add-matcher::.github/hadolint-matcher.json"
          make lint-docker
          echo "::remove-matcher owner=hadolint::"
      - name: Install shellcheck
        run: sudo apt-get install -y shellcheck
      - name: Lint Shell Scripts
        run: |
          echo "::add-matcher::.github/shellcheck-matcher.json"
          make lint-sh
          echo "::remove-matcher owner=shellcheck::"
