name: Lint with Hadolint
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3 # v3
      - name: Lint Dockerfiles
        run: |
          echo "::add-matcher::.github/hadolint-matcher.json"
          make lint-docker
          echo "::remove-matcher owner=hadolint::"
      - name: Install shellcheck
        run: sudo apt-get install -y shellcheck
      - name: Lint Shell Scripts
        run: |
          echo "::add-matcher::.github/shellcheck-matcher.json"
          make lint-sh
          echo "::remove-matcher owner=shellcheck::"
