name: Build Miniconda3 Nanoserver Image
on:
  push:
    branches:
      - master
    tags:
      - 'miniconda3-v*.*.*-nanoserver'
    paths:
      - 'miniconda3/nanoserver/Dockerfile'
      - '.github/workflows/miniconda_nanoserver_ci.yml'
  pull_request:
    paths:
      - 'miniconda3/nanoserver/Dockerfile'
      - '.github/workflows/miniconda_nanoserver_ci.yml'
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@24cb9080177205b6e8c946b17badbe402adc938f # v3

      - name: Login to DockerHub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a # tag=v2
        if: github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags')
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@507c2f2dc502c992ad446e3d7a5dfbe311567a96 # tag=v4
        with:
          images: continuumio/miniconda3
          tags: |
            type=ref,event=branch,suffix=-nanoserver
            type=ref,event=pr,suffix=-nanoserver
            type=match,pattern=miniconda3-v(.*)-nanoserver,group=1,suffix=-nanoserver
          flavor: |
            latest=false

      # The build push action does not support windows builds yet,
      # thus using raw commands https://github.com/docker/build-push-action/issues/18
      # TODO: Parse and use the meta action generated tag list
      - name: Build
        run: |
          echo "${{ steps.meta.outputs.tags }}"
          cd miniconda3/nanoserver && docker build . -t continuumio/miniconda3:master-nanoserver && docker image inspect continuumio/miniconda3:master-nanoserver

      - name: Push
        if: github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags')
        run: |
          cd miniconda3/nanoserver && docker push continuumio/miniconda3:master-nanoserver
