name: Build Miniconda3 Debian Image
on:
  push:
    branches:
      - main
    tags:
      - 'miniconda3-v*.*.*'
    paths:
      - 'miniconda3/debian/Dockerfile'
      - '.github/workflows/miniconda_debian_ci.yml'
  pull_request:
    paths:
      - 'miniconda3/debian/Dockerfile'
      - '.github/workflows/miniconda_debian_ci.yml'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4

      - name: Login to DockerHub
        uses: docker/login-action@465a07811f14bebb1938fbed4728c6a1ff8901fc # v2
        if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags')
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@68827325e0b33c7199eb31dd4e31fbe9023e06e3 # v2
        with:
          platforms: linux/amd64,linux/arm64,linux/ppc64le,linux/s390x

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@885d1462b80bc1c1c7f0b00334ad271f09369c55 # v2
        with:
          version: latest
          driver-opts: network=host

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@818d4b7b91585d195f67373fd9cb0332e31a7175 # v4
        with:
          images: continuumio/miniconda3
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=match,pattern=miniconda3-v(.*),group=1

      - name: build miniconda3/debian
        uses: docker/build-push-action@0a97817b6ade9f46837855d676c4cca3a2471fc9 # v4
        with:
          context: ./miniconda3/debian
          builder: ${{ steps.buildx.outputs.name }}
          file: ./miniconda3/debian/Dockerfile
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64,linux/arm64,linux/ppc64le,linux/s390x
          push: ${{ github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags') }}
