name: Build Miniconda3 Nanoserver Image
on:
  push:
    tags:
      - 'miniconda3-v*.*.*-nanoserver'
    paths:
      - 'miniconda3/nanoserver/Dockerfile'
      - '.github/workflows/miniconda_nanoserver_ci.yml'
  pull_request:
    paths:
      - 'miniconda3/nanoserver/Dockerfile'
      - '.github/workflows/miniconda_nanoserver_ci.yml'
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@1e204e9a9253d643386038d443f96446fa156a97

      - name: Login to DockerHub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        if: github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags')
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@548e2346a9987b56d8a4104fe776321ff8e23440
        with:
          images: continuumio/miniconda3
          tags: |
            type=ref,event=branch,suffix=-nanoserver
            type=ref,event=pr,suffix=-nanoserver
            type=match,pattern=miniconda3-v(.*)-nanoserver,group=1,suffix=-nanoserver
          flavor: |
            latest=false

      # The build push action does not support windows builds yet,
      # thus using raw commands https://github.com/docker/build-push-action/issues/18
      # TODO: Parse and use the meta action generated tag list
      - name: Build
        run: |
          echo "${{ steps.meta.outputs.tags }}"
          cd miniconda3/nanoserver && docker build . -t continuumio/miniconda3:master-nanoserver && docker image inspect continuumio/miniconda3:master-nanoserver

      - name: Push
        if: github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags')
        run: |
          cd miniconda3/nanoserver && docker push continuumio/miniconda3:master-nanoserver
